### ISSUE TITLE
Where is the romloader directory?

### ISSUE THREAD

**Issue by shooking** [sidecartridge/atarist-sidecart-firmware#28]
In your writeup you suggest ST_WORKING_DIR should be rooted in romloader.

I don't see it.
Hints appreciated.
I found I can build the images by using root of the git.

So has the code been refactored but docs lag?

**Comment by diegoparrilla** [comment]
`romloader` is the old name of the folder where the code is. The new name is `configurator`. I will fix that. The ST_WORKING_DIR is a hack to pass the source code folder to the Docker image. In my environment:

```
ST_WORKING_FOLDER=/Users/diego/wkspc/atarist-sidecart-firmware/configurator stcmd make DEBUG_MODE=1
```

Or you can use the `build.sh` script:

```
./build.sh /Users/diego/wkspc/atarist-sidecart-firmware release
```

Both must be executed from the root folder of the repository.

**Comment by shooking** [comment]
I added an issue with writeup om how to get your docker working on Windows. So I use you stcmd. I tend to use (backtick)pwd(backtick) for the subdir to root the dockers /tmp 

Just trying to debug your network code. I can see I need to change the configuration, build the rom, then swap over to the pico repo, change the network code, import my built rooms, build and flash my pico. And be careful about alignment. I need to determine if you are handling null termination consistently - not sure.

Thanks for all your creativity.
